import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline';

export type InitType = 'claude' | 'cursor' | 'agents';

// ---------------------------------------------------------------------------
// Templates — designed to score A (zero structural issues) out of the box.
// Rules satisfied: no empty sections, no duplicate headings, no heading-depth
// skips, all code blocks closed, negation ratio <60%, no TODO/FIXME, no
// hardcoded paths, tool list present when tools referenced, success criteria
// present in sections that contain task verbs.
// ---------------------------------------------------------------------------

const CLAUDE_TEMPLATE = `\
# Project Name — CLAUDE.md

> Agent instruction file generated by **agent-doctor**.
> Replace every \`[placeholder]\` before use.
> Validate: \`npx @chiragdarji/agent-doctor CLAUDE.md\`

## Project Overview

[One-paragraph description of what this project does and its main purpose.]

**Tech stack:** [e.g. TypeScript · Node.js · React]

**Repository layout:** [brief directory summary]

## Workflow

Each task follows this sequence:

1. Read the requirements and clarify any ambiguities before starting.
2. Identify which files need to change.
3. Make the minimal change that satisfies the requirement.
4. Run the test suite and linter to confirm correctness.
5. Summarise what changed and why in the commit message.

> ✅ **Success criteria:** A task is complete when all tests pass, the linter is clean, and the feature works end-to-end.

## Available Tools

The following tools and commands are available in this project:

| Command | Purpose |
|---------|---------|
| \`[test-command]\` | Run the full test suite |
| \`[build-command]\` | Compile / bundle the project |
| \`[lint-command]\` | Run the linter |
| \`[format-command]\` | Auto-format source files |

## Coding Standards

Write code that follows these standards:

- Use [language] strict mode throughout the codebase.
- Prefer named exports over default exports.
- Keep functions focused — one responsibility per function.
- Handle errors explicitly; do not swallow exceptions.
- Keep code readable without comments.

> ✅ **Success criteria:** Code is ready when it compiles without errors and all existing tests remain green.

## What NOT To Do

These actions are explicitly prohibited:

- Do not introduce breaking API changes without explicit approval.
- Do not commit secrets, credentials, or environment-specific values.
- Do not skip the test suite when fixing bugs.

Each prohibition has a preferred alternative — ask if unclear.

## Environment

Project runs on [OS / platform]. Key dependencies:

\`\`\`bash
# Install dependencies
[install-command]

# Verify setup
[verify-command]
\`\`\`

Avoid hardcoding machine-specific paths. Use environment variables or relative paths instead.
`;

const CURSOR_MDC_TEMPLATE = `\
---
description: "[Describe what these rules govern — e.g. TypeScript React component authoring]"
alwaysApply: true
---

# [Project] — Cursor Rules

> Generated by **agent-doctor**. Replace every \`[placeholder]\` before use.
> Validate: \`npx @chiragdarji/agent-doctor .cursor/rules/main.mdc\`

## Project Overview

[One-paragraph description of the project and its main purpose.]

**Tech stack:** [e.g. TypeScript · React · Tailwind CSS]

## Workflow

Each task follows this sequence:

1. Read the requirements and identify affected files.
2. Make the minimal change that satisfies the requirement.
3. Run tests and linting to confirm correctness.
4. Summarise what changed and why.

> ✅ **Success criteria:** A task is complete when tests pass, linting is clean, and the feature works as described.

## Coding Standards

- Follow [language] conventions and the project style guide.
- Keep functions focused — one responsibility per function.
- Handle errors explicitly; do not swallow exceptions.
- Prefer readable code over clever code.

## What NOT To Do

- Do not introduce breaking changes without explicit approval.
- Do not commit environment-specific secrets or absolute paths.

Each prohibition has a preferred alternative — ask if unclear.

## Environment

Project runs on [OS / platform]. Avoid hardcoding machine-specific paths; use relative paths or environment variables instead.
`;

const AGENTS_TEMPLATE = `\
# Project Name — AGENTS.md

> Agent instruction file generated by **agent-doctor**.
> Replace every \`[placeholder]\` before use.
> Validate: \`npx @chiragdarji/agent-doctor AGENTS.md\`

## Project Overview

[One-paragraph description of what this project does and its main purpose.]

**Tech stack:** [e.g. Python · FastAPI · PostgreSQL]

**Repository layout:** [brief directory summary]

## Workflow

Each task follows this sequence:

1. Read the requirements and clarify any ambiguities before starting.
2. Identify which files need to change.
3. Make the minimal change that satisfies the requirement.
4. Run the test suite and linter to confirm correctness.
5. Summarise what changed and why in the commit message.

> ✅ **Success criteria:** A task is complete when all tests pass, the linter is clean, and the feature works end-to-end.

## Available Tools

The following tools and commands are available in this project:

| Command | Purpose |
|---------|---------|
| \`[test-command]\` | Run the full test suite |
| \`[build-command]\` | Build the project |
| \`[lint-command]\` | Run the linter |

## Coding Standards

Write code that follows these standards:

- Follow [language] conventions and the project style guide.
- Keep functions focused — one responsibility per function.
- Handle errors explicitly; do not swallow exceptions.
- Keep code readable without comments.

> ✅ **Success criteria:** Code is ready when it passes lint checks and all tests remain green.

## What NOT To Do

These actions are explicitly prohibited:

- Do not introduce breaking API changes without explicit approval.
- Do not commit secrets, credentials, or environment-specific values.
- Do not skip the test suite when fixing bugs.

Each prohibition has a preferred alternative — ask if unclear.

## Environment

Project runs on [OS / platform]. Key dependencies:

\`\`\`bash
# Install dependencies
[install-command]

# Verify setup
[verify-command]
\`\`\`

Avoid hardcoding machine-specific paths. Use environment variables or relative paths instead.
`;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface InitOptions {
  type: InitType;
  cwd: string;
  force?: boolean;
}

export interface InitResult {
  filePath: string;
  type: InitType;
  existed: boolean;
}

interface TargetInfo {
  path: string;
  dir?: string;
}

function targetFor(type: InitType, cwd: string): TargetInfo {
  switch (type) {
    case 'claude':
      return { path: resolve(cwd, 'CLAUDE.md') };
    case 'agents':
      return { path: resolve(cwd, 'AGENTS.md') };
    case 'cursor':
      return {
        path: resolve(cwd, '.cursor', 'rules', 'main.mdc'),
        dir: resolve(cwd, '.cursor', 'rules'),
      };
  }
}

/**
 * Returns the template content string for the given init type.
 */
export function templateFor(type: InitType): string {
  switch (type) {
    case 'claude':
      return CLAUDE_TEMPLATE;
    case 'agents':
      return AGENTS_TEMPLATE;
    case 'cursor':
      return CURSOR_MDC_TEMPLATE;
  }
}

/** Prompts interactively; returns true if user confirmed, false if denied. */
async function promptOverwrite(filePath: string): Promise<boolean> {
  if (!process.stdin.isTTY) return false;

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((res) => {
    rl.question(`File already exists: ${filePath}\nOverwrite? [y/N] `, (answer) => {
      rl.close();
      res(answer.trim().toLowerCase() === 'y');
    });
  });
}

/**
 * Writes a well-structured agent instruction file template to disk.
 *
 * If the target file already exists and `opts.force` is not set, the user is
 * prompted interactively. Throws if the overwrite is declined.
 */
export async function initFile(opts: InitOptions): Promise<InitResult> {
  const { path: filePath, dir } = targetFor(opts.type, opts.cwd);
  const existed = existsSync(filePath);

  if (existed && !opts.force) {
    const confirmed = await promptOverwrite(filePath);
    if (!confirmed) {
      throw new Error(`Aborted — ${filePath} already exists. Use --force to overwrite.`);
    }
  }

  if (dir !== undefined) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(filePath, templateFor(opts.type), 'utf8');

  return { filePath, type: opts.type, existed };
}
